name: CI

on:
  push:
    branches: [main]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    name: bundle code

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    strategy:
      matrix:
        node-version: [15.x]

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: unfor19/install-aws-cli-action@v1
        with:
          version: 1.18.1

      - name: Run yarn install
        run: yarn install

      - name: Run yarn build
        run: yarn build

      - name: Create deployment directory
        run: mkdir -p dist/dashboard/${GITHUB_SHA}

      - name: move build files
        run: mv dist/*.* dist/dashboard/${GITHUB_SHA}

      - name: Deploy
        uses: reggionick/s3-deploy@v3
        with:
          folder: dist
          bucket: single-spa-react-demo
          bucket-region: us-east-1

  #      - name: Update import map
  #        run: chmod +x build/after_deploy.sh && build/after_deploy.sh

  update_import_map:
    needs: build

    runs-on: ubuntu-latest

    name: update_import_map

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      strategy:
        matrix:
          node-version: [15.x]

    steps:
      - uses: actions/checkout@v2
      - id: install-aws-cli
        uses: unfor19/install-aws-cli-action@v1
        with:
          version: 1.18.1
      - run: aws --version && ls -lah dist/
        shell: bash
